##Домашняя работа по методам оптимизации, 399 группа.
###Медведева Анна.

In [2]:
from scipy.optimize import linprog

import numpy as np
import pandas as pd
import math as math

<h5>Задача 1.</h5>
$$6 x_1 + x_2 + 8x_3 \longrightarrow \max$$
$$3 x_2 + 3 x_3 \leqslant 9$$
$$8 x_1 + 8 x_2 + 7 x_3 \leqslant 4$$

Приведем задачу к канонической: 
$$\langle \vec c, \vec x\rangle \rightarrow \max,$$
$$A \vec x \leqslant bound,$$
$$ x \geqslant \vec 0.$$

In [4]:
A = [[0,3,3],[8,8,7]]
bound = [9,4]
c = [-6,-1,-8]
bnds = [(0, None),(0,None),(0,None)]

In [5]:
res = linprog(c, A_ub=A, b_ub=bound, bounds=bnds)
print(res)

  status: 0
   slack: array([ 7.28571429,  0.        ])
 success: True
     fun: -4.5714285714285712
       x: array([ 0.        ,  0.        ,  0.57142857])
 message: 'Optimization terminated successfully.'
     nit: 1


Ответ:

In [14]:
print(res.x, -res.fun)

(array([ 0.        ,  0.        ,  0.57142857]), 4.5714285714285712)


<h5>Задача 2.</h5>

Найти субдифференциал функции:
$$ f = \max\{g_1, g_2\} = \max\{|9x + 9y|,|2x^2 + \frac{xy}{4} + y^2|\}.$$

Дифференциалы функций $g_1, g_2:$
$dg_1 = 9dx + 9dy, $ $dg_2 = (4x + y/4)dx + (2y + x/4)dy.$

Пусть точка $(x_0, y_0)$ удовлетворяет равенству:
$$ 9x + 9y = 2x^2 + \frac{xy}{4} + y^2,$$
и $g_1 > 0.$ Тогда cубдифференциал $f$ в этой точке имеет вид имеет вид:
$$df(x_0, y_0) = \{(9(1-t) + (4x + y/4)t)dx + (9(1-t) + (2y + x/4)t)dy\ |\ 0 \leqslant t \leqslant 1\}.$$
Точки, где $9x + 9y < 0$ и $-9x - 9y = 2x^2 + \frac{xy}{4} + y^2,$ симметричны вышерассмотренным относительно центра координат.
В точка, где $g_1 \not = g_2$ субдифференциал равен дифференциалу.

Ответ:
$$
    df =
    \begin{cases}
        9 sgn(x + y)(dx + dy), & g_1 > g_2 \\
        9 (4x + y/4)dx + (2y + x/8)dy, & g_1<g_2 \\
        (9 \cdot sgn(x + y)(1-t) + (4x + y/4)t)dx + (9 \cdot sgn(x + y)(1-t) + (2y + x/4)t)dy\ |\ 0 \leqslant t \leqslant 1\ , & g_1 = g_2.
    \end{cases}
$$

<h5>Задача 3.

$$ 9x + 8y \rightarrow min$$
$$ 9x^{2} - \frac{xy}{4} + 8y^{2} \leqslant 4$$

Функция Лагранжа имеет вид:
$$ L(x,y,\lambda) = 9x + 8y + \lambda(9x^{2} - \frac{xy}{4} + 8y^{2} -4).$$

Составим систему, приравняв производные к нулю:
$$ L'_{x} = 9 + 18\lambda x -\lambda y/4 = 0,$$
$$ L'_{y} = 8 - x\lambda/4 + 16y\lambda = 0.$$

Получаем:
$$ y = \frac{4(9+18x\lambda)}{\lambda} = \frac{36}{\lambda} + 72x,$$
$$ x = -\frac{64\cdot 36 + 32}{\lambda(16\cdot 4\cdot72 - 1)} = -\frac{2336}{4607\lambda} \approx -\frac{1}{2\lambda}$$

$$ y = \frac{36}{\lambda} - \frac{72\cdot 2336}{4607\lambda} = -\frac{2340}{4607\lambda} \approx -\frac{1}{2\lambda}.$$

Откуда $$ \lambda = \pm \frac{\sqrt{69}}{8}. $$
$$ \psi(\pm \frac{\sqrt{69}}{2}) = \mp \sqrt{69}.$$

$$x = y = \frac{4}{\sqrt{69}} - \text{минимум.}$$

Ответ: $\lambda = -\frac{\sqrt{69}}{8}$ решение двойственной задачи, $x = y = \frac{4}{\sqrt{69}}$ решение исходной задачи.

<h5>Задача 5.</h5>
$$f(x_1,x_2) = 3x_1^2 - x_1x_2/8 + x_2^2 + x_2 \longrightarrow \min$$

Начальное приближение: $(7,7).$


Будем пользоваться:
$$\vec x_{k+1} = \vec x_k - a_k\cdot f'(\vec x_k),$$

где $a_k$ - точка минимума $g(\alpha) = f(\vec x_k+\alpha \vec d_k)$

$$grad f(x_1,x_2) = (6x_1 - x_2/8, -x_1/8 + 2x_2 + 1).$$ 

Напишем несколько функций, упрощяющих вычисления.

In [ ]:
def f(x_1,x_2):
    return 3 * (x_1 ** 2 - x_1 * x_2 /8.0 + x_2 ** 2 + x_2

In [41]:
def g(x_1,x_2, d_1, d_2, alpha):
    return f(x_1 + alpha*d_1, x_2 + alpha*d_2)

In [65]:
def grad_f(x_1, x_2):
    return np.array([6 * x_1 - x_2 / 8., -x_1 / 8. + 2 * x_2 + 1])

Посчитаем направление убывания функции.

In [75]:
x_0 = np.array([7,7])
decrease_direction = -grad_f(7, 7)
print decrease_direction

[-41.125 -14.125]


Найдем минимум функции $g(\alpha)$.

In [82]:
alpha = np.linspace(-100,100,1000001)
func_g = g(x_0[0], x_0[1], decrease_direction[0], decrease_direction[1], alpha)
min_alpha_1 = min(zip(func_g,alpha))[1]
min_alpha_1

0.18180000000000973

In [83]:
epsilon = 0.25
alpha = np.linspace(min_alpha_1 - epsilon, min_alpha_1 + epsilon,1000001)
func_g = g(x_0[0], x_0[1], decrease_direction[0], decrease_direction[1], alpha)
min_alpha_2 = min(zip(func_g,alpha))[1]
min_alpha_2

0.18178150000000973

In [78]:
def calculate_next_x_k(x, alpha):
    return np.array(x - alpha*grad_f(x[0],x[1]))

Посчитаем следующее приближение:

In [80]:
x_1 = calculate_next_x_k(x_0, min_alpha_2)

Ответ:

In [81]:
print x_1

[-0.47576419  4.43233631]


<h5>Задача 6.</h5>

$$ f(x_1, x_2) = 2x_1^2 - (x_1x_2)/3 + x_2^2 \longrightarrow \min,$$
$$ \vec x_0 = (0,9),$$
$$ \alpha_0 = \hat \alpha = 1,$$
$$ \varepsilon = \theta =1/2$$

Пользуемся $\alpha_i = \theta \cdot \alpha_{i-1},$ если 
$$ f(x_k - \alpha d_k) < f(x_k) - \varepsilon \alpha \langle f'(x_k), d_k \rangle.$$

In [149]:
def f(x):
    return 2*x[0] ** 2 - (x[0] * x[1])/3 + x[1] ** 2.

In [177]:
def grad_f(x):
    return np.array([4*x[0] - x[1]/3.0, -x[0]/3.0 + 2*x[1]])

In [178]:
x_0 = np.array([0,9])
eps = 0.5
theta = 0.5
alpha_0 = 1
decrease_direction_0 = -grad_f(x_0)
decrease_direction_0

array([  3., -18.])

In [179]:
def armicho_rull(x, alpha, decrease_direction):
    temp = int(np.matrix(grad_f(x)) * np.transpose(np.matrix(decrease_direction)))
    #print f(x - alpha * decrease_direction), f(x) - eps * alpha * temp, eps * alpha * temp
    return f(x - alpha * decrease_direction) < f(x) - eps * alpha * temp

Проверим выполнение условия Армихо.

In [180]:
armicho_rull(x_0, alpha_0, decrease_direction_0)

False

Как видно, условие Армихо не выполняется, поэтому алгоритм продолжается.

In [181]:
alpha_1 = theta * alpha_0

In [182]:
def calculate_next_x_k(x, decrease_direction, alpha):
    return np.array(x + alpha*decrease_direction)

In [183]:
x_1 = calculate_next_x_k(x_0, decrease_direction_0, alpha_0)
x_1

array([ 3., -9.])

In [184]:
decrease_direction_1 = -grad_f(x_1)

In [185]:
armicho_rull(x_1, alpha_1, decrease_direction_1)

False

Условие снова не выполняется.

In [186]:
alpha_2 = theta * alpha_1

In [188]:
x_2 = calculate_next_x_k(x_1, decrease_direction_1, alpha_1)
decrease_direction_2 = -grad_f(x_2)

In [190]:
armicho_rull(x_2, alpha_2, decrease_direction_2)

False

Вторая итерация закончена.

<h5>Задача 7.</h5>

$$ \sin(x_1) + \cos(x_2/7) + \sin(x_1/9)\sin(x_2/8) \longrightarrow \min$$

$$\text{Начальное приближение:} (\pi/9, \pi/9).$$

In [235]:
math.sin(1)

0.8414709848078965

Метод Ньютона для функций многих переменных: $x_{i+1} = x_i - (f''(x_i))^{-1}f'(x_i)$. 

In [215]:
def f(x):
    return math.sin(x[0]) + math.cos(x[1]/7.) + math.sin(x[1]/9.)*math.sin(x[1]/8.)

In [289]:
def grad_f(x):
    return np.array([math.cos(x[0]) + (1/9.) * math.cos(x[0]/9.) * math.sin(x[1]/8.),\
                    (-1/7.) * math.sin(x[1]/7.) + (1/8.) * math.cos(x[1]/8.) * math.sin(x[0]/9.)])


In [308]:
def double_grad_f(x):
    return np.matrix([[(- 1) * math.sin(x[0]) - (1/81.) * math.sin(x[0]/9.) * math.sin(x[1]/8.), 
                       (1/72.) * math.cos(x[0]/9.) * math.sin(x[1]/8.)],
                      [-(1/49.) * math.cos(x[1]/7.) - (1/64.) * math.sin(x[1]/8.) * math.sin(x[0]/9.),
                       (1/72.) * math.cos(x[0]/9.) * math.sin(x[1]/8.)]])

In [351]:
x_1 = np.transpose(np.matrix(x_0)) - np.matrix(double_grad_f(x_0) ** (-1) * np.transpose(np.matrix(grad_f(x_0))))

In [375]:
x_1 = np.transpose(x_1)
x_1

array([   3.29284846,  103.35867249])

In [385]:
x_2 = np.transpose(np.matrix(x_1)) - np.matrix(double_grad_f(x_1) ** (-1) * np.transpose(np.matrix(grad_f(x_1))))

In [386]:
x_2 = (np.transpose(x_2))
x_2

matrix([[   9.61289495,  105.59215593]])

Вторая итерация закончена.

<h5>Задача 8.</h5>

$$ 7x_1^2 - \frac{x_1\cdot x_2}{6} + 2x_2^2 \longrightarrow \min$$
$$ 4x_1 + 2x_2 = 1$$
$$ x_0 = (0, 1/4)$$

Сведем задачу к стандартной : 
$$f(x) = \frac{1}{2}(Qx,x)$$
$$ Ax = b$$

Посчитаем оператор проектирования по формуле : $P = E - A^T(A \cdot A^T)^{-1}A.$

In [404]:
A = np.matrix([[4,2]])
b = 1
Q = np.matrix([[14, -1/6.],[-1/6., 4]])
P = np.transpose(A) * (A * np.transpose(A)) ** (-1) * A
E = np.matrix([[1,0],[0,1]])
P = E - P
P

matrix([[ 0.2, -0.4],
        [-0.4,  0.8]])

In [396]:
x_0 = np.array([0, 1/4.])
step_1 = grad_f(x_0)
step_1

array([-0.04166667,  1.        ])

Найдем $y$ из равенства: $P\cdot Q\cdot P\cdot y = -P \cdot Q \cdot x_0.$

In [405]:
A = P* Q * P

In [410]:
B = - P * Q * np.transpose(np.matrix(x_0))

In [411]:
B

matrix([[ 0.40833333],
        [-0.81666667]])

In [414]:
y = A ** (-1) * B
y

matrix([[ 0.25  ],
        [-0.0625]])

In [417]:
x_new = np.transpose(np.matrix(x_0)) + P * y

In [418]:
x_new

matrix([[ 0.075],
        [ 0.1  ]])

Ответ: $(0.075, 0.1).$

<h5>Задача 9.</h5>

$$x_1^2 - \frac{x_1\cdot x_2}{3} + 5x_2^2 + 4x_2 \longrightarrow \min$$
$$ 4x_1 + 8x_2 = 6.$$

Заметим, что $f$ практически квадратичная форма, поэтому возьмем квадратичную штраф-функцию: $P(x) = (4x_1 + 8x_2 - 6)^2$, тогда исходная задача сводится к задаче минимизации функции $g_r(x_1 x_2) = x_1^2 - (x_1x_2)/3 + 5x_2^2 + 4x_2 + r(4x_1 + 8x_2 - 6)^2$.

Решаем систему относительно $r$:
$$ g'_{x_1} = 2x_1 - x_2/3 + 2r\cdot 4(4x_1 + 8x_2 - 6) = 0,$$
$$ g'_{x_2} = -x_1/3 + 10x_2 + 4 + 2r\cdot 8(4x_1 + 8x_2 - 6) = 0.$$

$$x_1 = \frac{x_2/3 - 8r(8x_2 - 6)}{2(1+16r)}$$

$$ -\frac{x_2/3 - 8r(8x_2 - 6)}{3 \cdot 2(1+16r)} + 10x_2 + 4 + 2r\cdot 8\cdot \left( \frac{4(x_2/3 - 8r(8x_2 - 6))}{2(1+16r)}  + 8x_2 - 6\right) = 0$$

$$-x_2/3 + 8r(8x_2 - 6) + 12(5x_2 + 2)(1 + 16r) + 16r(12(x_2/3 - 8r(8x_2 - 6)) + 3(8x_2 - 6)) = 0$$

$$-x_2/3 + 64rx_2 - 48r + 60(1 + 16r)x_2 + 24(1 + 16r) + 16r(4x_2 - 12\cdot8r(8x_2 - 6)) + 16\cdot 3r(8x_2 - 6) = 0$$

$$x_2(-1/3 + 64r + 12\cdot5(1 + 16r) + 24\cdot16r + 16r\cdot 4 - 16\cdot 12\cdot 64 \cdot r^2 + 24\cdot 16r) + -48r + 24(1+16r) + 16\cdot 48 \cdot 12 \cdot r^2 - 48\cdot r\cdot 6= 0$$

$$ x_2 = \frac{- 9216r^2 -48r - 24}{12288r^2 + 1856r + 59.6} = f_2(r) $$

$$x_1 = \frac{ \frac{- 9216r^2 -48r - 24}{3\cdot(12288r^2 + 1856r + 59.6)} - 8r(8\frac{- 9216r^2 -48r - 24}{12288r^2 + 1856r + 59.6} - 6)}{2(1+16r)} = f_1(r)$$

In [24]:
-9216/12288.

-0.75

$$ x^*_2 = \lim_{r \rightarrow \infty}f_2(r) = \frac{-9216}{12288} = -0.75$$

$$ x_1^* = \lim_{r \rightarrow \infty} f_1(r) = 3.$$

Ответ: $x^*_1 = 0.75, x_2^* = 3.$

<h5>Задача 10.</h5>

$$f(x_1, x_2) = 9x_1^2 - 2x_1x_2 + 6x_2^2 + 9x_1 \longrightarrow \min $$
$$ 7x_1 + 2x_2 \leqslant 9$$

Возьмем $P(x)= \max^2(7x_1 + 2x_2 - 9, 0),$ тогда исходная задача сводится к минимизации функции
$$ g_r(x_1, x_2) = 9x_1^2 - 2x_1x_2 + 6x_2^2 + 9x_1 + r (\max(7x_1 + 2x_2 - 9, 0))^{2}.$$

Рассмотрим возможные случаи:

1) $7x_1 + 2x_2 - 9 \geqslant 0.$
$$ g(x_1,x_2) = 9x_1^2 - 2x_1x_2 + 6x_2^2 + 9x_1 + r(7x_1 + 2x_2)^2 - 18r(7x_1 + 2x_2) + 81r.$$

$$g'_{x_1} = 18x_1 - 2x_2 + 9 + 2r(7x_1 + 2x_2)\cdot 7 - 18r\cdot 7 = 0,$$
$$ g'_{x_2} = -2x_1 + 12x_2 + 2r(7x_1 + 2x_2)\cdot 2 - 2\cdot 18r = 0.$$

Откуда получаем:
$$ (4r-2)x_2 = -18x_1 - 9 - 14rx_1 +  126r$$
$$ x_2 = \frac{-18x_1 - 9 - 14rx_1 +  126r}{(4r-2)}.$$
Подставляя во второе равенство для производных, получаем:

$$-2x_1 + 6\frac{-18x_1 - 9 - 14rx_1 +  126r}{(2r-1)} + 2r(14x_1 + 2\frac{-18x_1 - 9 - 14rx_1 +  126r}{(2r-1)}) - 2\cdot 18r = 0,$$

$$-2x_1(2r - 1) + 6(-18x_1 - 9 - 14rx_1 +  126r) + 14rx_1(4r-2) + 4r(-18x_1 - 9 - 14rx_1 +  126r) - 36(2r-1)r = 0,$$

$$ x_1(2 - 4r - 6\cdot (18 + 14r) + 28r(2r-1) + 4r(-18 - 14r)) + 6(126r - 9) + 4r(-9 + 126r) -36(2r-1) = 0,$$
$$ x_1 = -\frac{6(126r - 9) + 4r(-9 + 126r) -36(2r-1)}{2 - 4r - 6\cdot (18 + 14r) + 28r(2r-1) + 4r(-18 - 14r)} = f_1(r).$$

И тогда $x_1^* = \lim_{r \rightarrow \infty} f_1(r) = -9 $.

In [38]:
4*126/56.

9.0

In [39]:
9*14/4

31

$x_2^* = \lim_{r \rightarrow \infty} f_2(r) = 31$

In [33]:
def f(x):
    return 9 * x[0] ** 2 - 2 * x[0] * x[1] + 6 * x[1] ** 2 + 9 * x[0]

Посчитаем значение функции в найденных точках.

In [47]:
x_1 = np.array([-9, 31])

In [48]:
f(x_1)

6972

2) $7x_1 + 2x_2 - 9 \geqslant 0$
$ g(x_1,x_2) = 9x_1^2 - 2x_1x_2 + 6x_2^2 + 9x_1. $

$$g'_{x_1} = 18x_1 - 2x_2 + 9 = 0,$$
$$ g'_{x_2} = -2x_1 + 12x_2 = 0.$$

$$x_1 = 6x_2$$
$$18\cdot6x_2 - 2x_2 + 9 = 0$$
$$x_2 = -\frac{9}{106}, x_1 = -\frac{27}{53}.$$

In [42]:
-9/106.

-0.08490566037735849

In [43]:
-27/53.

-0.5094339622641509

In [45]:
x_2 = np.array([-0.50943,-0.08490])
f(x_2)

-2.2924528299000002

Ответ: $f(x_2) < f(x_1),$ значит точка $(-0.51, -0.08)$ является минимумом f при заданных условиях.

<h5>Задача 11.</h5>

In [5]:
import matplotlib.pyplot as plt
game = pd.read_csv("game_1.csv")
game

First\Second  L  C  R  RR
0            U  1  5  0  -2
1            D -2  3  7   9

Данные подобраны так, чтобы не было доминирующих стратегий.

In [3]:
p = np.linspace(0, 1, 3)
l_1 = p - 2 * (1 - p)
l_2 = 5 * p + 3 * (1 - p)
l_3 = 7 * (1 - p)
l_4 = -2 * p + 9 * (1 - p)

In [ ]:
plt.figure(figsize=(20, 6))
plt.plot(p, l_1, '-', c='red')
plt.plot(p, l_2, '-', c='blue')
plt.plot(p, l_3, '-', c='black')
plt.plot(p, l_4, '-', c='green')
x_peresechenie = 0.784
y_peresechenie = x_peresechenie - 2 * (1 - x_peresechenie)
plt.plot(x_peresechenie, y_peresechenie, 'o', c='black')
plt.show()

<img src="figure_2.png">

В точке $A$ достигается максимум нижней огибающей. Ее координаты находим из уравнения: $3 \cdot p - 2 = -11 \cdot p + 9,$ откуда $p = \frac{11}{14}$, смешанная стратегия первого: $(11/14, 3/14).$ 

Для второго игрока смешанная стратегия:
$$3q - 11(1-q) = 0,$$
$$q = \frac{11}{14}.$$

Итак, $(11/14, 3/14)$ - смешанная стратегия первого, $(11/14, 0, 0, 3/14)$ - смешанная стратегия второго.
Решение игры: $u = 3/14,$ оно же седловая точка.